//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace session
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirPlaneEntities1 : DbContext
    {
        public AirPlaneEntities1()
            : base("name=AirPlaneEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirPlaneT> AirPlaneTs { get; set; }
        public virtual DbSet<flight_attendant> flight_attendant { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<pilot> pilots { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Airline> Airlines { get; set; }
    }
}
