//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace session
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirPlaneT
    {
        public int Id { get; set; }
        public string AirPlane_Name { get; set; }
        public string company_Name { get; set; }
        public byte[] Logo { get; set; }
        public int Capacity { get; set; }
        public string YearMade { get; set; }
        public int SeriesNumber { get; set; }
        public byte[] img { get; set; }
    }
}
