//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace session
{
    using System;
    using System.Collections.Generic;
    
    public partial class flight_attendant
    {
        public string Code { get; set; }
        public string year_employment { get; set; }
        public byte[] personal_img { get; set; }
        public string birthday { get; set; }
        public string Email { get; set; }
        public string character { get; set; }
        public string Name { get; set; }
        public string family { get; set; }
        public string Airline { get; set; }
        public byte[] AirLineLogo { get; set; }
    }
}
