//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace session
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UserName { get; set; }
        public string firstName { get; set; }
        public string LastName { get; set; }
        public string Passwords { get; set; }
        public string Email { get; set; }
        public string Birthday { get; set; }
        public byte[] img { get; set; }
    }
}
